# Generated by Django 4.1 on 2022-08-24 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mnemonic', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='braincenter.series')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='series_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='braincenter.seriestype'),
        ),
    ]
